CarRental.UI/Controllers/CarController.cs
using CarRental.BLL;
using CarRental.Model;
using CarRental.UI.ViewsModels.Car;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRental.UI.Controllers
{
    public class CarController : Controller
    {
        private readonly CarLogic carLogic;
        private readonly CarModelLogic carModelLogic;
        private readonly CarMakeLogic carMakeLogic;
        private readonly BookingLogic bookingLogic;
        private readonly RequestBookingLogic requestBookingLogic;
        private readonly EventLogic eventLogic;
        private readonly AdressLogic addressLogic;
        private readonly UtilisateurLogic utilisateurLogic;
        private readonly StatusLogic statusLogic;
        private readonly StopOverLogic stopOverLogic;
        private readonly StopOverAddressLogic stopOverAddressLogic;
        private readonly NotificationLogic notificationLogic;
        private readonly CompanyLogic companyLogic;

        public CarController()
        {
            companyLogic = new CompanyLogic();
            carLogic = new CarLogic();
            carModelLogic = new CarModelLogic();
            carMakeLogic = new CarMakeLogic();
            bookingLogic = new BookingLogic();
            requestBookingLogic = new RequestBookingLogic();
            eventLogic = new EventLogic();
            addressLogic = new AdressLogic();
            utilisateurLogic = new UtilisateurLogic();
            statusLogic = new StatusLogic();
            stopOverLogic = new StopOverLogic();
            stopOverAddressLogic = new StopOverAddressLogic();
            notificationLogic = new NotificationLogic();
        }

        // GET: Voiture
        public ActionResult Index()
        {
            CarIndexViewsModel vm = new CarIndexViewsModel
            {
                CarsMakes = GetCarsMakes(),
                Companys = GetCompanys()
            };

            int idCurrentUser = (int)Session["userId"];
            Session["notifs"] = notificationLogic.ListAllForUser(idCurrentUser).FindAll(n => n.IsRead == 0).Count;

            return View(vm);
        }

        public ActionResult SearchCar(string searchWord)
        {

            return null;
        }

        public ActionResult _ListCars(string licencePlate)
        {
            List<CarDTO> _cars = new List<CarDTO>();

            if (string.IsNullOrWhiteSpace(licencePlate))
            {
                _cars = carLogic.List();
            }
            else
            {
                _cars = carLogic.List(licencePlate);
            }

            List<Tuple<CarDTO, CarModelDTO, CarMakeDTO>> cars = new List<Tuple<CarDTO, CarModelDTO, CarMakeDTO>>();


            foreach (CarDTO car in _cars)
            {
                CarModelDTO carModel = carModelLogic.Get(car.id_Car_Model);
                CarMakeDTO carMake = carMakeLogic.Get(carModel.id_Car_Make);

                cars.Add(new Tuple<CarDTO, CarModelDTO, CarMakeDTO>(car, carModel, carMake));
            }

            CarIndexListCarViewsModel vm = new CarIndexListCarViewsModel
            {
                Cars = cars
            };

            return PartialView(vm);
        }

        public ActionResult GetCarsModels(int idMake)
        {
            List<CarModelDTO> carsModels = carModelLogic.List(idMake);

            if (HttpContext.Request.IsAjaxRequest())
                return Json(new SelectList(carsModels, "Id", "Model"), JsonRequestBehavior.AllowGet);

            return View(carsModels);
        }

        private IEnumerable<SelectListItem> GetCarsMakes()
        {
            List<CarMakeDTO> dbCarsMakes= carMakeLogic.List();

            var carsMakes = dbCarsMakes.Select(x => new SelectListItem
            {
                Value = x.id.ToString(),
                Text = x.Make
            });

            return new SelectList(carsMakes, "Value", "Text");
        }

        private IEnumerable<SelectListItem> GetAddresses()
        {
            List<AddressDTO> addresses = addressLogic.List();

            var addressesList = addresses.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });

            return new SelectList(addressesList, "Value", "Text");
        }
        private IEnumerable<SelectListItem> GetCompanys()
        {
            List<CompanyDTO> companys = companyLogic.List();

            var companyList = companys.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            });

            return new SelectList(companyList, "Value", "Text");
        }

        [HttpGet]
        public ActionResult RendreCar(int idBooking)
        {
            CarRendreCarViewsModel vm = new CarRendreCarViewsModel();

            BookingDTO booking = bookingLogic.Get(idBooking);
            RequestBookingDTO requestBooking = requestBookingLogic.GetByRequestBooking(booking.id_Request_Booking);
            StopOverDTO stopOver = stopOverLogic.GetByBooking(booking.Id);
            List<UserDTO> passagersAller = utilisateurLogic.ListPassagers(booking.Id, 1);
            List<UserDTO> passagersRetour = utilisateurLogic.ListPassagers(booking.Id, 0);
            StatusDTO status = statusLogic.GetStatus(requestBooking.Id_Status);
            StopOverAddressDTO stopOverAddress = stopOverAddressLogic.GetStopOverAddress(stopOver.Id);
            UserDTO driverAller = utilisateurLogic.GetDriver(booking.Id, 1);
            UserDTO driverRetour = utilisateurLogic.GetDriver(booking.Id, 0);
            AddressDTO addressAller = addressLogic.GetAddress(booking.Id, 1);
            AddressDTO addressRetour = addressLogic.GetAddress(booking.Id, 0);
            UserDTO createdBy = utilisateurLogic.Get(requestBooking.CreateBy);

            Booking _booking = new Booking
            {
                booking = booking,
                requestBooking = requestBooking,
                stopOver = stopOver,
                passagersAller = passagersAller,
                passagerRetour = passagersRetour,
                status = status,
                stopOverAddress = stopOverAddress,
                driverAller = driverAller,
                driverRetour = driverRetour,
                addressRetour = addressRetour,
                addressAller = addressAller,
                createdBy = createdBy
            };

            vm.Booking = _booking;

            return View(vm);
        }

        [HttpPost]
        public ActionResult RendreCar(int kilometrage, int idBooking, string LicencePlate)
        {
            BookingDTO booking = bookingLogic.Get(idBooking);
            RequestBookingDTO requestBooking = requestBookingLogic.GetByRequestBooking(booking.id_Request_Booking);
            requestBookingLogic.Update(requestBooking.id, 4);

            carLogic.Update(LicencePlate, kilometrage);

            return RedirectToAction("Index", "Booking");
        }

        public ActionResult Detail(string licencePlate)
        {
            CarDTO car = carLogic.Get(licencePlate);
            CarModelDTO carModel = carModelLogic.Get(car.id_Car_Model);
            CarMakeDTO carMake = carMakeLogic.Get(carModel.id_Car_Make);
            List<BookingDTO> bookings = bookingLogic.List(car.Licence_Plate);
            List<EventDTO> events = eventLogic.List(licencePlate);


            CarDetailViewsModel vm = new CarDetailViewsModel
            {
                car = car,
                carModel = carModel,
                carMake = carMake,
                events = events
            };

            return View(vm);
        }

        public ActionResult GetCalendarData(string start, string end, string licencePlate)
        {
            List<EventDTO> events = eventLogic.List(licencePlate);
            List<BookingDTO> bookings = bookingLogic.List(licencePlate);

            List<FullCalendarDTO> fullCalendars = new List<FullCalendarDTO>();

            if(events is null)
            {

            } else
            {
                foreach (EventDTO @event in events)
                {
                    fullCalendars.Add(new FullCalendarDTO { Id = @event.Id, Libelle = @event.Libelle, Start = @event.Start_Date.ToString("yyyy-MM-dd"), End = @event.End_Date.ToString("yyyy-MM-dd") });
                }

                foreach (BookingDTO booking in bookings)
                {
                    RequestBookingDTO requestBooking = requestBookingLogic.Get(booking.Id);

                    fullCalendars.Add(new FullCalendarDTO { Id = booking.Id, Libelle = requestBooking.Reason });
                }
            }

          
            return Json(fullCalendars.Select(e => new { id = e.Id, title = e.Libelle, start = e.Start, end = e.End }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddCar(HttpPostedFileBase CarImage, CarIndexViewsModel vm, int dropdownlistCarsModels, int CompanyId, string Licence_Plate, int Mileage, string Energy)
        {
            CarDTO car = new CarDTO
            {
                Energy_Value = Energy,
                id_Car_Model = dropdownlistCarsModels,
                is_Active = 1,
                is_Available = 1,
                Licence_Plate = Licence_Plate,
                Mileage = Mileage,
                Id_User = (int)Session["userId"],
                Id_Company = CompanyId
            };

            if (CarImage != null && CarImage.ContentLength > 0)
                try
                {
                    string extension = Path.GetExtension(CarImage.FileName);
                    string filename = Licence_Plate;

                    string newFile = filename + extension;

                    string path = Path.Combine(Server.MapPath("~/Images/Cars"), newFile);
                    CarImage.SaveAs(path);
                }
                catch (Exception ex)
                {

CarRental.UI/Controllers/ConfigurationController.cs
using CarRental.BLL;
using CarRental.Model;
using CarRental.UI.ViewsModels.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRental.UI.Controllers
{
    public class ConfigurationController : Controller
    {
        private readonly RoleLogic roleLogic;
        private readonly ActionLogic actionLogic;
        private readonly NotificationLogic notificationLogic;

        public ConfigurationController()
        {
            roleLogic = new RoleLogic();
            actionLogic = new ActionLogic();
            notificationLogic = new NotificationLogic();
        }

        /// <summary>
        /// Affiche la page de configuration
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            
            ConfigurationIndexViewModel Civm = new ConfigurationIndexViewModel()
            {
                ListRoleWithActionTuple = actionLogic.GetListTupleRoleAction(roleLogic.List())
            };

            int idCurrentUser = (int)Session["userId"];
            Session["notifs"] = notificationLogic.ListAllForUser(idCurrentUser).FindAll(n => n.IsRead == 0).Count;

            return View(Civm);
        }
        
    }
}

CarRental.UI/Controllers/NotificationController.cs
using CarRental.BLL;
using CarRental.Model;
using CarRental.UI.ViewsModels.Notification;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CarRental.UI.Controllers
{
    public class NotificationController : Controller
    {
        private readonly NotificationLogic notifLogic;
        private readonly UtilisateurLogic userLogic;
        private readonly AdressLogic addressLogic;
        private readonly BookingLogic bookingLogic;
        private readonly RequestBookingLogic requestBookingLogic;

        public NotificationController()
        {
            notifLogic = new NotificationLogic();
            userLogic = new UtilisateurLogic();
            addressLogic = new AdressLogic();
            bookingLogic = new BookingLogic();
            requestBookingLogic = new RequestBookingLogic();
        }

        /**
         * GET: Notification
         * Page d'index de la liste des notifications
         */
        public ActionResult Index()
        {
            int idCurrentUser = (int)Session["userId"];
            List<NotificationDTO> notifs = notifLogic.ListAllForUser(idCurrentUser);
            NotificationIndexViewModel vm = new NotificationIndexViewModel
            {
                Notifications = GetNotificationsTuples(notifLogic.ListAllForUser(idCurrentUser))
            };
            Session["notifs"] = notifLogic.ListAllForUser(idCurrentUser).FindAll(n => n.IsRead == 0).Count;
            return View(vm);
        }

        /**
         * GetNotificationsTuples
         * Transforme une list de NotificationDTO en Tuple pour la NotificationIndexViewModel
         */
        private List<(NotificationDTO notification, RequestBookingDTO requestBooking, UserDTO user, string departureCity)> GetNotificationsTuples(List<NotificationDTO> list)
        {
            List<(NotificationDTO notification, RequestBookingDTO requestBooking, UserDTO user, string departureCity)> newList = 
                new List<(NotificationDTO notification, RequestBookingDTO requestBooking, UserDTO user, string departureCity)>();

            if (list != null)
            {
                foreach (NotificationDTO notif in list)
                {
                    RequestBookingDTO reqBooking = new RequestBookingDTO();
                    reqBooking = requestBookingLogic.Get(notif.IdRequestBooking);

                    UserDTO user = new UserDTO();
                    user = userLogic.Get(reqBooking.CreateBy);

                    int idBooking = bookingLogic.GetByRequestBooking(reqBooking.id).Id;
                    AddressDTO address = addressLogic.GetAddress(idBooking);
                    string departureCity = "Non précisé";
                    if (address.Name != null)
                    {
                        departureCity = address.Name;
                    }
                    else if (address.Locality != null)
                    {
                        departureCity = address.Locality;
                    }

                    newList.Add((notif, reqBooking, user, departureCity));
                    if (notif.IsRead == 0)
                    {
                        notifLogic.MarkAsRead(notif.Id);
                    }
                }
            }
            
            return newList;
        }


    }
}

CarRental.UI/Views/Shared/LoginLayout.cshtml
@model CarRental.Model.UserDTO
@{
    if (Session["firstName"] != null)
    {
        Response.Redirect("~/Home/Index");
    }
    else
    {


        <!DOCTYPE html>
        <html>
        <head>
            <meta name="viewport" content="width=device-width" />
            <title>@ViewBag.Title</title>
            <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
            <link href="~/Content/AdminLTE.min.css" rel="stylesheet" />
            <link href="~/Content/Ionicons/css/ionicons.min.css" rel="stylesheet" />
            <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
            <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet" />
            <link href="~/Content/Site.css" rel="stylesheet" />
        </head>
        <body class="hold-transition login-page">
            <div class="login-box">
                <div class="login-logo">
                    <a href="/"><b>Car</b>Rental</a>
                </div>
                <!-- /.login-logo -->
                <div class="login-box-body">
                    @RenderBody()
                </div>
                <!-- /.login-box-body -->
            </div>
            <!-- /.login-box -->
            <script src="~/Scripts/jquery-3.3.1.min.js"></script>
            <script src="~/Scripts/jquery.validate.min.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        </body>
    </html>
        }
    }

CarRental.UI/Views/Shared/_Layout.cshtml
@using CarRental.Common
@{
    if (Session["firstName"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
    else
    {


        int userId = Session["userId"] != null ? Int32.Parse(Session["userId"].ToString()) : -1;
        var profilePath = ImageHelper.GetProfileImagePath(userId, Server);

    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <title>@ViewBag.Title - Mon application ASP.NET</title>
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/fullcalendar")
        @Styles.Render("~/Content/select2")
        <script src="~/Scripts/modernizr-2.8.3.js"></script>
       
        
        
    </head>
    <body class="hold-transition skin-blue sidebar-mini">

        <div class="wrapper">
            <header class="main-header">
                <a href="@Url.Action("Index", "Home")" class="logo">
                    <span class="logo-mini"><b>E</b>NI</span>
                    <span class="logo-lg"><b>Locations</b> ENI</span>
                </a>

                <nav class="navbar navbar-static-top">
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="navbar-custom-menu">

                        <ul class="nav navbar-nav">
                            <!---->
                            <li class="notifications-menu">
                                <a href="@Url.Action("Index", "Notification")" id="notifsLink">
                                    <i class="fa fa-bell-o"></i>
                                    @if ((int)Session["notifs"] > 0)
                                    {
                                        <span class="label label-warning">
                                            @Session["notifs"].ToString()
                                        </span>
                                    }
                                    else
                                    {
                                        <span class="label label-info">
                                            @Session["notifs"].ToString()
                                        </span>
                                    }

                                </a>
                            </li>

                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="@Url.Content(profilePath)" class="user-image" alt="User Image">
                                    <span class="hidden-xs">@Session["firstName"].ToString() @Session["lastName"].ToString()</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="user-header">
                                        <img src="@Url.Content(profilePath)" class="img-circle" alt="User Image">

                                        <p>
                                            @Session["firstName"].ToString() @Session["lastName"].ToString()
                                            <small>@Session["userJob"].ToString()</small>
                                        </p>
                                    </li>
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="@Url.Action("Index", "Profile")" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="@Url.Action("LogOut", "Account")" class="btn btn-default btn-flat">Déconnexion</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>

            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="@Url.Content(profilePath)" class="img-circle" alt="User Image">
                        </div>
                        <div class="pull-left info">
                            <p>@Session["firstName"].ToString() @Session["lastName"].ToString()</p>
                            <a href="#">@Session["userJob"].ToString()</a>
                        </div>
                    </div>

                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu" data-widget="tree">
                        <li>
                            <a href="@Url.Action("Index", "Home")">
                                <i class="fa fa-dashboard"></i> <span>Accueil</span>
                                <span class="pull-right-container">
                                </span>
                            </a>
                        </li>

                        <!-- my customer area-->
                        <li class="header">MON ESPACE</li>
                        <li>
                            <a href="@Url.Action("Index", "Profile")">
                                <i class="fa fa-user"></i> <span>Mon profil</span>
                                <span class="pull-right-container">
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Notification")">
                                <i class="fa fa-bell"></i> <span>Notifications</span>
                                @if ((int)Session["notifs"] > 0)
                                {
                                    <span class="pull-right-container">
                                        <small class="label pull-right bg-red">
                                            @Session["notifs"].ToString()
                                        </small>
                                    </span>
                                }
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Booking")">
                                <i class="fa fa-map-pin"></i> <span>Mes réservations</span>
                            </a>
                        </li>

                        <!-- administrator area -->
                        <li class="header">ADMINISTRATEUR</li>
                        <li>
                            <a href="@Url.Action("Validations", "Booking")">
                                <i class="fa fa-check"></i> <span>Demandes à valider</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Utilisateur")">
                                <i class="fa fa-users"></i> <span>Utilisateurs</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Car")">
                                <i class="fa fa-car"></i> <span>Voitures</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Configuration")">
                                <i class="fa fa-cog"></i> <span>Configuration</span>
                            </a>
                        </li>

                        <!-- deconnexion -->
                        <li class="header">PLUS</li>
                        <li>
                            <a href="@Url.Action("LogOut", "Account")">
                                <i class="fa fa-sign-out text-red"></i> <span class="text-red">Deconnexion</span>
                                <span class="pull-right-container">
                                </span>
                            </a>
                        </li>
                    </ul>
                </section>
            </aside>

            <div class="content-wrapper">
                @RenderBody()

            </div>
        </div>


        <script src="~/Scripts/jquery-3.3.1.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/modernizr-2.8.3.js"></script>
        <script src="~/Scripts/adminlte.min.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>
        <script src="~/Scripts/moment.js"></script>
        <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
        <script src="~/Scripts/demo.js"></script>
        <script src="~/Scripts/car.js"></script>
        <script src="~/Scripts/Select2/select2.full.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
        <script src="~/Scripts/FullCalendarCoreMain.js"></script>
        <script src="~/Scripts/fullCalendarDaygridmain.js"></script>
        <script src="~/Scripts/chart.js"></script>
        <script src="~/Scripts/dashboard2.js"></script>
        <script src="~/Scripts/moment-with-locales.min.js"></script>
        <script src="~/Scripts/fr.js"></script>
        @RenderSection("scripts", required: false)
    </body>
</html>
        }
    }